# Generated by Django 3.0.14 on 2022-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_products_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
