# Generated by Django 3.0.14 on 2022-07-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_auto_20220721_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
    ]
