# Generated by Django 3.0.14 on 2022-07-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_products_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
    ]
