# Generated by Django 3.0.14 on 2022-07-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_auto_20220721_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='salesitems',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='salesitems',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='sales',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='discounted_amount',
            field=models.FloatField(default=0),
        ),
    ]
