# Generated by Django 3.0.14 on 2022-07-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_auto_20220721_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='discounted_amount',
        ),
    ]
