# Generated by Django 3.0.14 on 2022-08-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_auto_20220725_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='chart_stock',
            field=models.IntegerField(default=0),
        ),
    ]
