# Generated by Django 4.1.3 on 2022-11-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0014_inventoryrecord_salesitems_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
