# Generated by Django 4.1.3 on 2022-11-17 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0016_alter_inventoryrecord_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
