# Generated by Django 4.1.3 on 2022-11-17 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0017_alter_inventoryrecord_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 15, 59, 34, 175699, tzinfo=datetime.timezone.utc)),
        ),
    ]
