# Generated by Django 4.1.3 on 2022-11-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0019_alter_inventoryrecord_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='date_added',
            field=models.DateField(),
        ),
    ]
