# Generated by Django 4.1.3 on 2022-11-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0022_alter_inventoryrecord_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
