# Generated by Django 4.1.3 on 2022-11-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0023_inventoryrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrecord',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
