# Generated by Django 4.1.3 on 2022-11-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0024_inventoryrecord_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryrecord',
            old_name='product_id',
            new_name='product_record_id',
        ),
        migrations.RemoveField(
            model_name='inventoryrecord',
            name='discount',
        ),
    ]
