# Generated by Django 4.1.3 on 2022-11-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0025_rename_product_id_inventoryrecord_product_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='product_record_id',
            field=models.CharField(max_length=100),
        ),
    ]
