# Generated by Django 4.1.3 on 2022-11-25 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0027_remove_inventoryrecord_product_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='st_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
