# Generated by Django 4.1.3 on 2022-11-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0028_alter_inventoryrecord_st_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='st_date',
            field=models.DateTimeField(),
        ),
    ]
