# Generated by Django 4.1.3 on 2023-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0038_alter_inventoryrecord_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='product_name',
            field=models.TextField(),
        ),
    ]
