# Generated by Django 4.1.3 on 2023-01-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0041_alter_inventoryrecord_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.products'),
        ),
    ]
