# Generated by Django 4.1.3 on 2023-01-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0042_alter_inventoryrecord_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='st_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
